query GetProduct($id: ID!) {
  product(id: $id) {
    ...ProductFields
    variants(first: 250) {
      edges {
        cursor
        node {
          ...VariantFields
        }
      }
    }
  }
}

$product.fragment.gql

$variant.fragment.gql
