query searchProducts($query: String!, $first: Int!, $after: String) {
  products(first: $first, query: $query, after: $after) {
    edges {
      node {
        id
        title
        description
        handle
        productType
        vendor
        tags
        priceRange {
          minVariantPrice {
            amount
            currencyCode
          }
        }
        images(first: 1) {
          edges {
            node {
              url
              altText
            }
          }
        }
      }
      cursor
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
