query searchProducts($query: String!, $limit: Int!, $cursor: String!) {
    products(
      query: $query
      first: $limit
      sortKey: RELEVANCE
      after: $cursor
    ) {
      edges {
        cursor
        node {
          $product.fragment.gql
        }
      }
    }
  }
