query getCollection($id: ID!) {
  collection(id: $id) {
    id
    title
    description
    handle
    updatedAt
    image {
      url
      altText
      width
      height
    }
    products(first: 20) {
      edges {
        node {
          id
          title
          handle
          priceRange {
            minVariantPrice {
              amount
              currencyCode
            }
          }
          images(first: 1) {
            edges {
              node {
                url
                altText
              }
            }
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
