query searchProducts($query: String!, $first: Int!) {
    products(
      query: $query
      first: $first
      sortKey: RELEVANCE
    ) {
      edges {
        cursor
        node {
          $product.fragment.gql
        }
      }
    }
  }
