query getCollection($id: ID!, $first: Int!, $sortKey: CollectionSortKeys!) {
  collection(id: $id) {
    $collection.fragment.gql
    products(first: $first, sortKey: $sortKey, after: $after) {
      edges {
        node {
          id
          title
          handle
          priceRange {
            minVariantPrice {
              amount
              currencyCode
            }
          }
          images(first: 1) {
            edges {
              node {
                url
                altText
              }
            }
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
