query getCollection($id: ID!) {
  collection(id: $id) {
    $collection.fragment.gql
    products(first: 20) {
        edges {
            cursor
            node {
                $product.fragment.gql
            }
        }
      pageInfo {
        hasNextPage
        endCursor
      }
  }
  }
}
