query product($handle: String!, $firstVariants: Int = 1) {
    product(handle: $handle) {
        ...ProductFields
        variants(first: $firstVariants) {
            edges {
                node {
                    ...VariantFields
                }
            }
        }
    }
}

# storefrontAPI 2025-07
fragment ProductFields on Product {
$product.fragment.gql
}
fragment VariantFields on ProductVariant {
$variant.fragment.gql
}
