
    id
    title
    productType
    descriptionHtml
    category{
        name
    }
    tags
    vendor
    handle
    description
    handle
    productType
    vendor
    tags
    createdAt
    updatedAt
    publishedAt
    priceRange {
        minVariantPrice {
            amount
            currencyCode
        }
        maxVariantPrice {
            amount
            currencyCode
        }
    }
    media(first: 10) {
        edges {
            node {
                id
                alt
                mediaContentType
                previewImage {

                    altText
                    height
                    width
                    url

                }

            }
        }
    }
    options {
        id
        name
        optionValues {
            id
            name
        }
    }
