query searchProducts($query: String!, $first: Int!,$sortKey: String!,$reverse: boolean!) {
    products(
        query: $query
        first: $first
        sortKey: $sortKey
        reverse: $reverse
    ) {
        edges {
            cursor
            node {
            $product.fragment.gql
        }
    }
}
}
